sudo: false
language: python
python:
    - 3.5
    - 3.6
addons:
  apt:
    sources:
      - sourceline: 'ppa:tah83/secp256k1'
    packages:
      - libsecp256k1-0
install:
  - pip install -r contrib/requirements/requirements-travis.txt
cache:
  - pip: true
  - directories:
    - /tmp/electrum-build
script:
    - tox
after_success:
    - if [ "$TRAVIS_BRANCH" = "master" ]; then pip install pycurl requests && contrib/make_locale; fi
    - coveralls
jobs:
  include:
    - stage: binary builds
      sudo: true
      language: c
      python: false
      env:
        - TARGET_OS=Windows
      services:
        - docker
      install: true
      script:
        - sudo docker build --no-cache -t electrum-img -f ./contrib/build-wine/docker/Dockerfile .
      after_success: true
    - os: osx
      language: c
      env:
        - TARGET_OS=macOS
      python: false
      install:
        - git fetch --all --tags
        - git fetch origin --unshallow
      script: ./contrib/build-osx/make_osx
      after_script: ls -lah dist && md5 dist/*
      after_success: true
    - stage: release check
      install:
          - git fetch --all --tags
          - git fetch origin --unshallow
      script:
        - ./contrib/deterministic-build/check_submodules.sh
      after_success: true
      if: tag IS present
